
export const MERGE_COLLEGEOPTIONS_PROVINCE= "MERGE_COLLEGEOPTIONS_PROVINCE";
export const MERGE_COLLEGEOPTIONS_LEVEL = 'MERGE_COLLEGEOPTIONS_LEVEL';
export const MERGE_COLLEGEOPTIONS_TYPE  = 'MERGE_COLLEGEOPTIONS_TYPE';
export const MERGE_COLLEGEOPTIONS_COLLEGEPROP = 'MERGE_COLLEGEOPTIONS_COLLEGEPROP';
export const MERGE_COLLEGEOPTIONS_INPUT = 'MERGE_COLLEGEOPTIONS_INPUT';
export const MERGE_CURRENTPAGE = 'MERGE_CURRENTPAGE';
export const MERGE_COLLEGERESULT = 'MERGE_COLLEGERESULT'

//院校库

//获取院校类别列表
export const GET_COLLEGELIB_CONDITIONS = "GET_COLLEGELIB_CONDITIONS";
//通过筛选条件返回大学列表
export const GET_COLLEGELIB_COLLEGELIST = "GET_COLLEGELIB_COLLEGELIST";
//通过大学ID返回大学详情
export const GET_COLLEGELIB_COLLEGEDETAIL= "GET_COLLEGELIB_COLLEGEDETAIL";