//所有程序中用到的有关此模块的actionID 都引用于此 ****必须全局唯一*****

//获取MBTI测试结果
export const GET_ASSESSCENTER_MBTI_REPORT = "GET_ASSESSCENTER_MBTI_REPORT";
//获取HOLLAND 测试结果
export const GET_ASSESSCENTER_HOLLAND_REPORT = "GET_ASSESSCENTER_HOLLAND_REPORT";


// 提交MI测试答案
export const SUBMIT_ASSESSCENTER_MI_ANSWERS = "SUBMIT_ASSESSCENTER_MI_ANSWERS";

// 提交价值观测试答案
export const SUBMIT_ASSESSCENTER_VALUE_ANSWERS = "SUBMIT_ASSESSCENTER_VALUE_ANSWERS";
