
//所有程序中用到的有关此模块的actionID 都引用于此 ****必须全局唯一*****
// 获取MI测试题目
export const GET_MIASSESS_QUIZZES = "GET_MIASSESS_QUIZZES";
//提交MI测试的答案
export const SUBMIT_MIASSESS_ANSWERS = 'SUBMIT_MIASSESS_ANSWERS';
//获取多元智能测试是否完成的状态
export const GET_MIASSESS_MIASSWSSFINISHSTATE = 'GET_MIASSESS_MIASSWSSFINISHSTATE';
//获取MI测试引导页导语
export const GET_MIASSESS_INTRODUCTION = "GET_MIASSESS_INTRODUCTION";
// 获取MI测试结果
export const GET_MIASSESS_MI_REPORT = "GET_MIASSESS_MI_REPORT";