
export const MERGE_SUBJ_CLASSIFICATION= "MERGE_SUBJ_CLASSIFICATION";
export const MERGE_SUBJ_CATEGORIES = 'MERGE_SUBJ_CATEGORIES';
export const MERGE_MAJOR_CATEGORIES = 'MERGE_MAJOR_CATEGORIES';
export const MERGE_MAJOR_CLICKFLAG  = 'MERGE_MAJOR_CLICKFLAG';
export const MERGE_MAJOR_SEARCHVAL = 'MERGE_MAJOR_SEARCHVAL';
export const MERGE_MAJOR_SHOW_WHO ='MERGE_MAJOR_SHOW_WHO';

export const MERGE_CURRENTPAGE = 'MERGE_CURRENTPAGE';

export const MERGE_MAJORRESULT = 'MERGE_MAJORRESULT'

//学科库

//获取学科库
export const GET_MAJORLIB_MAJORLIB = "GET_MAJORLIB_MAJORLIB";
//获取学科详细解读
export const GET_MAJORLIB_MAJORDETAIL = "GET_MAJORLIB_MAJORDETAIL";

//通过筛选条件返回列表
export const GET_MAJORLIB_MAJORLIST = "GET_MAJORLIB_MAJORLIST";