
/*
export const MERGE_JOBOPTIONS_JOB= "MERGE_JOBOPTIONS_JOB";
export const MERGE_JOBOPTIONS_INPUT = 'MERGE_JOBOPTIONS_INPUT';
*/


//获取职业信息
export const GET_JOBLIB_JOBLIB = "GET_JOBLIB_JOBLIB";

export const GET_JOBLIB_JOBINTRODUCTION = "GET_JOBLIB_JOBINTRODUCTION";

export const GET_JOBLIB_SEARCHRESULT = "GET_JOBLIB_SEARCHRESULT";
