
//所有程序中用到的有关此模块的actionID 都引用于此 ****必须全局唯一*****


// 公共 获取最新动态
export const GET_COMMON_ACTIVITIES = "GET_COMMON_ACTIVITIES";


// 公共 获取关注人数与粉丝人数
export const GET_COMMON_SOCIALINFO = "GET_COMMON_SOCIALINFO";

//取消好友关注
export const SET_COMMON_CANCELFOLLOWED = "SET_COMMON_CANCELFOLLOWED";
//加好友关注
export const SET_COMMON_BECOMEFOLLOWER = "SET_COMMON_BECOMEFOLLOWER";

export const ADD_COMMON_VISITRECORD = "ADD_COMMON_VISITRECORD";

export const GET_COMMON_OTHERUSERREGIONSCHOOLINFO = "GET_COMMON_OTHERUSERREGIONSCHOOLINFO";
export const SET_COMMON_COMMENT = "SET_COMMON_COMMENT";
export const GET_COMMON_NOTIFICATIONS = "GET_COMMON_NOTIFICATIONS";
export const SET_COMMON_LIKE = "SET_COMMON_LIKE";
export const GET_COMMON_NATIVEPLACEINFO = "GET_COMMON_NATIVEPLACEINFO";
export const GET_COMMON_SELFUSERINFO = "GET_COMMON_SELFUSERINFO";
export const SET_COMMON_SELFUSERINFO = "SET_COMMON_SELFUSERINFO";
export const SET_COMMON_PASSWORD = "SET_COMMON_PASSWORD";
export const SET_COMMON_ADVICE = "SET_COMMON_ADVICE";
