
//所有程序中用到的有关此模块的actionID 都引用于此 ****必须全局唯一*****

//学生学期整体分析

//获取班级积分排名
export const GET_STUDENT_RANKINCLASS = "GET_STUDENT_RANKINCLASS";
// 获取成长积分记录
export const GET_STUDENT_INTEGRALSCORERECORD = "GET_STUDENT_INTEGRALSCORERECORD";
// 获取月度总结 // 保存月度总结
export const GET_STUDENT_MONTHSUMMARY = "GET_STUDENT_MONTHSUMMARY";
export const SET_STUDENT_MONTHSUMMARY = "SET_STUDENT_MONTHSUMMARY";
// 获取学期总结 // 保存学期总结
export const GET_STUDENT_SEMESTERSUMMARY = "GET_STUDENT_SEMESTERSUMMARY";
export const SET_STUDENT_SEMESTERSUMMARY = "SET_STUDENT_SEMESTERSUMMARY";
export const SET_STUDENT_SEMESTERQUALITYSUMMARY = "SET_STUDENT_SEMESTERQUALITYSUMMARY";

// 获取老师评语
export const GET_STUDENT_TEACHEREVALUATE = "GET_STUDENT_TEACHEREVALUATE";
// 获取学业水平记录
export const GET_STUDENT_SCORE = "GET_STUDENT_SCORE";
// 获取综合素质档案
export const GET_STUDENT_COMPREHENSIVEQUALITYRECORD = "GET_STUDENT_COMPREHENSIVEQUALITYRECORD";

// 同学互评
export const GET_EVALUATE_STUDENT_STAR = "GET_EVALUATE_STUDENT_STAR";
//同学互评 ---  我的星星得分
export const GET_EVALUATE_STUDENT_MYSELF_STAR = "GET_EVALUATE_STUDENT_MYSELF_STAR";