
//所有程序中用到的有关此模块的actionID 都引用于此 ****必须全局唯一*****

//获取老师的个人信息
export const READ_TEACHER_USERINFO = "READ_TEACHER_USERINFO";

// 获取班主任页面拥有的菜单
export const GET_TEACHER_MODULECONFIG = "GET_TEACHER_MODULECONFIG";

// 班主任 获取班级同学列表
export const GET_TEACHER_CLASSMATELIST = "GET_TEACHER_CLASSMATELIST";

// 班主任
// 获取班级排名状态
export const GET_TEACHER_RANKSTATE = "GET_TEACHER_RANKSTATE";

// 获取过往通知 发送班级通知 获取班级通知  删除班级通知
export const GET_TEACHER_CLASSNOTIFICATION = "GET_TEACHER_CLASSNOTIFICATION";
export const SET_TEACHER_CLASSNOTIFICATION = "SET_TEACHER_CLASSNOTIFICATION";
export const DELETE_TEACHER_CLASSNOTIFICATION = "DELETE_TEACHER_CLASSNOTIFICATION";
// 获取班级积分排名
export const GET_TEACHER_RANKINCLASS = "GET_TEACHER_RANKINCLASS";

// 获取过往班团活动 新增班团活动 修改班团活动 删除班团活动
export const READ_TEACHER_ACTIVITY = "READ_TEACHER_ACTIVITY";
export const SAVE_TEACHER_ACTIVITY = "SAVE_TEACHER_ACTIVITY";
export const DELETE_TEACHER_ACTIVITY = "DELETE_TEACHER_ACTIVITY";

// 添加学生表现前 获取表现所需的列表
export const READ_TEACHER_STUDENTPERFORMANCEOPTIONS = "READ_TEACHER_STUDENTPERFORMANCEOPTIONS";

// 获取学生过往表现记录 获取表现记录类型列表 新增表现记录 删除表现记录
export const READ_TEACHER_STUDENTPERFORMANCE_RECORD = "READ_TEACHER_STUDENTPERFORMANCE_RECORD";
export const SAVE_TEACHER_STUDENTPERFORMANCE_RECORD = "SAVE_TEACHER_STUDENTPERFORMANCE_RECORD";
export const DELETE_TEACHER_STUDENTPERFORMANCE_RECORD = "DELETE_TEACHER_STUDENTPERFORMANCE_RECORD";

// 获取特殊学生列表 添加特殊学生 移除特殊学生
export const READ_TEACHER_SPECIALSTUDENT = "READ_TEACHER_SPECIALSTUDENT";
export const CREATE_TEACHER_SPECIALSTUDENT = "CREATE_TEACHER_SPECIALSTUDENT";
export const DELETE_TEACHER_SPECIALSTUDENT = "DELETE_TEACHER_SPECIALSTUDENT";

// 获取特殊学生的过往情况分析记录 新增特殊学生的情况分析记录 修改特殊学生的情况分析记录 删除特殊学生的情况分析记录
export const READ_TEACHER_SPECIALSTUDENT_RECORD = "READ_TEACHER_SPECIALSTUDENT_RECORD";
export const SAVE_TEACHER_SPECIALSTUDENT_RECORD = "SAVE_TEACHER_SPECIALSTUDENT_RECORD";
export const DELETE_TEACHER_SPECIALSTUDENT_RECORD = "DELETE_TEACHER_SPECIALSTUDENT_RECORD";

// 获取此学生此学期的星星评价 提交此学生此学期的星星评价
export const GET_TEACHER_EVALUATESTUDENT_STAR = "GET_TEACHER_EVALUATESTUDENT_STAR";
export const SET_TEACHER_EVALUATESTUDENT_STAR = "SET_TEACHER_EVALUATESTUDENT_STAR";

// 获取老师对此学生此学期的学期整体评价 提交老师对此学生此学期的学期整体评价
export const GET_TEACHER_TERMEVALUATE = "GET_TEACHER_TERMEVALUATE";
export const SET_TEACHER_TERMEVALUATE = "SET_TEACHER_TERMEVALUATE";

// 获取此年月此学生的班主任月度评语 提交此年月此学生的班主任月度评语
export const SET_TEACHER_MONTHEVALUATE = "SET_TEACHER_MONTHEVALUATE";

// 获取此年月此学生的月度总结
export const GET_TEACHER_STUDENTMONTHSUMMARY = "GET_TEACHER_STUDENTMONTHSUMMARY";


//使用老师管理学生评语处请求，获取评价学生选项列表，前台需要处理为树形结构
export const GET_TEACHER_STUTERMQUALITYEVALUATIONITEMS = "GET_TEACHER_STUTERMQUALITYEVALUATIONITEMS";

//老师管理学生评语 列表
export const READ_TEACHER_EVALUATESTUDENTDICT = "READ_TEACHER_EVALUATESTUDENTDICT";
//添加/修改评语字典
export const SAVE_TEACHER_REVIEWWORD = "SAVE_TEACHER_REVIEWWORD";
//删除评语字典
export const DELETE_TEACHER_REVIEWWORD = "DELETE_TEACHER_REVIEWWORD";

//提交素质评价的结果 一个方面 三个小方面
export const SUBMIT_TEACHER_STUTERMQUALITYEVALUATION = "SUBMIT_TEACHER_STUTERMQUALITYEVALUATION";
